//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserLeisure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserLeisure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string btnAdvanced {
            get {
                return ResourceManager.GetString("btnAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Reset.
        /// </summary>
        internal static string btnDontReset {
            get {
                return ResourceManager.GetString("btnDontReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string btnExpert {
            get {
                return ResourceManager.GetString("btnExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string btnMaster {
            get {
                return ResourceManager.GetString("btnMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        internal static string btnNovice {
            get {
                return ResourceManager.GetString("btnNovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string btnQuit {
            get {
                return ResourceManager.GetString("btnQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string btnRepeat {
            get {
                return ResourceManager.GetString("btnRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string btnResume {
            get {
                return ResourceManager.GetString("btnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string dlgActive {
            get {
                return ResourceManager.GetString("dlgActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Level completed.
        /// </summary>
        internal static string dlgAllDone {
            get {
                return ResourceManager.GetString("dlgAllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hit a bomb, all tools are reset..
        /// </summary>
        internal static string dlgBomb {
            get {
                return ResourceManager.GetString("dlgBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Points.
        /// </summary>
        internal static string dlgBonus {
            get {
                return ResourceManager.GetString("dlgBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level completed.
        /// </summary>
        internal static string dlgCompleted {
            get {
                return ResourceManager.GetString("dlgCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string dlgDone {
            get {
                return ResourceManager.GetString("dlgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freestyle.
        /// </summary>
        internal static string dlgFreestyle {
            get {
                return ResourceManager.GetString("dlgFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string dlgInfo {
            get {
                return ResourceManager.GetString("dlgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ladder.
        /// </summary>
        internal static string dlgLadder {
            get {
                return ResourceManager.GetString("dlgLadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Selection.
        /// </summary>
        internal static string dlgLevelSelection {
            get {
                return ResourceManager.GetString("dlgLevelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level not completed.
        /// </summary>
        internal static string dlgNotCompleted {
            get {
                return ResourceManager.GetString("dlgNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game paused.
        /// </summary>
        internal static string dlgPause {
            get {
                return ResourceManager.GetString("dlgPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Points.
        /// </summary>
        internal static string dlgPenalty {
            get {
                return ResourceManager.GetString("dlgPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        internal static string dlgPoints {
            get {
                return ResourceManager.GetString("dlgPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ladder progress?.
        /// </summary>
        internal static string dlgResetLadder {
            get {
                return ResourceManager.GetString("dlgResetLadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string dlgStatus {
            get {
                return ResourceManager.GetString("dlgStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Points.
        /// </summary>
        internal static string dlgTime {
            get {
                return ResourceManager.GetString("dlgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Costs.
        /// </summary>
        internal static string dlgTools {
            get {
                return ResourceManager.GetString("dlgTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        internal static string dlgTotal {
            get {
                return ResourceManager.GetString("dlgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the highscore list.
        /// </summary>
        internal static string enteruser {
            get {
                return ResourceManager.GetString("enteruser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time High.
        /// </summary>
        internal static string highScoreAll {
            get {
                return ResourceManager.GetString("highScoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        internal static string highScoreCaption {
            get {
                return ResourceManager.GetString("highScoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        internal static string highscoreHeader {
            get {
                return ResourceManager.GetString("highscoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string highScoreLocal {
            get {
                return ResourceManager.GetString("highScoreLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/requestscores_ll.php.
        /// </summary>
        internal static string highScoreRequestURL {
            get {
                return ResourceManager.GetString("highScoreRequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/newscore_ll.php.
        /// </summary>
        internal static string highScoreSendURL {
            get {
                return ResourceManager.GetString("highScoreSendURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string highScoreUpdate {
            get {
                return ResourceManager.GetString("highScoreUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ of the Week.
        /// </summary>
        internal static string highScoreWeek {
            get {
                return ResourceManager.GetString("highScoreWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.soundjay.com.
        /// </summary>
        internal static string infoAudioContent {
            get {
                return ResourceManager.GetString("infoAudioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio:.
        /// </summary>
        internal static string infoAudioLabel {
            get {
                return ResourceManager.GetString("infoAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laser@phoebit.com.
        /// </summary>
        internal static string infoContactContent {
            get {
                return ResourceManager.GetString("infoContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string infoContactLabel {
            get {
                return ResourceManager.GetString("infoContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com.
        /// </summary>
        internal static string infoHowtoContent {
            get {
                return ResourceManager.GetString("infoHowtoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Webpage:.
        /// </summary>
        internal static string infoHowtoLabel {
            get {
                return ResourceManager.GetString("infoHowtoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string infoVersion {
            get {
                return ResourceManager.GetString("infoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string instGeneral {
            get {
                return ResourceManager.GetString("instGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Leisure is puzzle game and a brain teaser..
        /// </summary>
        internal static string instGeneralLine1 {
            get {
                return ResourceManager.GetString("instGeneralLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place tools on the workbench to bend and split laser beams to hit targets..
        /// </summary>
        internal static string instGeneralLine2 {
            get {
                return ResourceManager.GetString("instGeneralLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid obstacles which will absorb your beams. Some obstacles explode when hit..
        /// </summary>
        internal static string instGeneralLine3 {
            get {
                return ResourceManager.GetString("instGeneralLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep an eye on the time counter. The laser will fire automatically when it reaches zero..
        /// </summary>
        internal static string instGeneralLine4 {
            get {
                return ResourceManager.GetString("instGeneralLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score points and play on the ladder or play freestyle without competition..
        /// </summary>
        internal static string instGeneralLine5 {
            get {
                return ResourceManager.GetString("instGeneralLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string instHeader {
            get {
                return ResourceManager.GetString("instHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        internal static string instLaser {
            get {
                return ResourceManager.GetString("instLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are different kinds of lasers available. Tap a laser to fire them all. .
        /// </summary>
        internal static string instLaserLine1 {
            get {
                return ResourceManager.GetString("instLaserLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never hit a laser with a beam or it will break and the level can&apos;t be fulfilled..
        /// </summary>
        internal static string instLaserLine2 {
            get {
                return ResourceManager.GetString("instLaserLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit all the targets with a beam of the corresponding color. .
        /// </summary>
        internal static string instLaserLine3 {
            get {
                return ResourceManager.GetString("instLaserLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitting a target with the wrong beam breaks the target and the level must be repeated..
        /// </summary>
        internal static string instLaserLine4 {
            get {
                return ResourceManager.GetString("instLaserLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacles.
        /// </summary>
        internal static string instObstacles {
            get {
                return ResourceManager.GetString("instObstacles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls block the path of the beam. They will absorb a beam..
        /// </summary>
        internal static string instObstaclesLine1 {
            get {
                return ResourceManager.GetString("instObstaclesLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid to hit a bomb at all costs. An exploding bomb resets your level setup..
        /// </summary>
        internal static string instObstaclesLine2 {
            get {
                return ResourceManager.GetString("instObstaclesLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed tools have the same function as the standard tools but they can&apos;t be moved..
        /// </summary>
        internal static string instObstaclesLine3 {
            get {
                return ResourceManager.GetString("instObstaclesLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser are obstacles to all beams..
        /// </summary>
        internal static string instObstaclesLine4 {
            get {
                return ResourceManager.GetString("instObstaclesLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets are obstacles to all beams except the to color matching beams..
        /// </summary>
        internal static string instObstaclesLine5 {
            get {
                return ResourceManager.GetString("instObstaclesLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string instPoints {
            get {
                return ResourceManager.GetString("instPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points per level are accumulated in ladder mode only. .
        /// </summary>
        internal static string instPointsLine1 {
            get {
                return ResourceManager.GetString("instPointsLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing a difficulty stage of 10 levels will send the points to the leaderboard..
        /// </summary>
        internal static string instPointsLine2 {
            get {
                return ResourceManager.GetString("instPointsLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You start each level with 100 points. Each failed laser shot deducts 10 points..
        /// </summary>
        internal static string instPointsLine3 {
            get {
                return ResourceManager.GetString("instPointsLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can score up to 9 bonus points by setting up a workbench quickly..
        /// </summary>
        internal static string instPointsLine4 {
            get {
                return ResourceManager.GetString("instPointsLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bonus item randomly shows up at the first laser shot. Gain 30 points with a hit..
        /// </summary>
        internal static string instPointsLine5 {
            get {
                return ResourceManager.GetString("instPointsLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the crosshair to help placing the tools..
        /// </summary>
        internal static string instToolLine1 {
            get {
                return ResourceManager.GetString("instToolLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mirror reflects or absorbs the beam, depending on which side the beam hits it..
        /// </summary>
        internal static string instToolLine2 {
            get {
                return ResourceManager.GetString("instToolLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The semi-mirror splits the beam. One split is reflected the other goes straight through..
        /// </summary>
        internal static string instToolLine3 {
            get {
                return ResourceManager.GetString("instToolLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The triangular splitter creates two beams out of one. .
        /// </summary>
        internal static string instToolLine4 {
            get {
                return ResourceManager.GetString("instToolLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wood tool doesn&apos;t change the direction but the speed of the beam..
        /// </summary>
        internal static string instToolLine5 {
            get {
                return ResourceManager.GetString("instToolLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string instTools {
            get {
                return ResourceManager.GetString("instTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/games.
        /// </summary>
        internal static string moreGamesURL {
            get {
                return ResourceManager.GetString("moreGamesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/news/news.php.
        /// </summary>
        internal static string newsURL {
            get {
                return ResourceManager.GetString("newsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freestyle.
        /// </summary>
        internal static string optionFreestyle {
            get {
                return ResourceManager.GetString("optionFreestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fx.
        /// </summary>
        internal static string optionFX {
            get {
                return ResourceManager.GetString("optionFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionHeader {
            get {
                return ResourceManager.GetString("optionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder.
        /// </summary>
        internal static string optionLadder {
            get {
                return ResourceManager.GetString("optionLadder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string optionMusic {
            get {
                return ResourceManager.GetString("optionMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        internal static string optionName {
            get {
                return ResourceManager.GetString("optionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string optionsAudio {
            get {
                return ResourceManager.GetString("optionsAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string optionsMode {
            get {
                return ResourceManager.GetString("optionsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string optionsName {
            get {
                return ResourceManager.GetString("optionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/.
        /// </summary>
        internal static string phoebitURL {
            get {
                return ResourceManager.GetString("phoebitURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string welcomePlay {
            get {
                return ResourceManager.GetString("welcomePlay", resourceCulture);
            }
        }
    }
}
