//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTrouble.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainTrouble.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all level done, send mail for more.
        /// </summary>
        internal static string allDone {
            get {
                return ResourceManager.GetString("allDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username for the highscore list.
        /// </summary>
        internal static string enteruser {
            get {
                return ResourceManager.GetString("enteruser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound FX.
        /// </summary>
        internal static string fx {
            get {
                return ResourceManager.GetString("fx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string gameOver {
            get {
                return ResourceManager.GetString("gameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string goon {
            get {
                return ResourceManager.GetString("goon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscore.
        /// </summary>
        internal static string highscore {
            get {
                return ResourceManager.GetString("highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time High.
        /// </summary>
        internal static string highScoreAll {
            get {
                return ResourceManager.GetString("highScoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        internal static string highScoreCaption {
            get {
                return ResourceManager.GetString("highScoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string highScoreLocal {
            get {
                return ResourceManager.GetString("highScoreLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/requestscores_tt.php.
        /// </summary>
        internal static string highScoreRequestURL {
            get {
                return ResourceManager.GetString("highScoreRequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/newscore_tt.php.
        /// </summary>
        internal static string highScoreSendURL {
            get {
                return ResourceManager.GetString("highScoreSendURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string highScoreUpdate {
            get {
                return ResourceManager.GetString("highScoreUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ of the Week.
        /// </summary>
        internal static string highScoreWeek {
            get {
                return ResourceManager.GetString("highScoreWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.soundjay.com.
        /// </summary>
        internal static string infoAudioContent {
            get {
                return ResourceManager.GetString("infoAudioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio:.
        /// </summary>
        internal static string infoAudioLabel {
            get {
                return ResourceManager.GetString("infoAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train@phoebit.com.
        /// </summary>
        internal static string infoContactContent {
            get {
                return ResourceManager.GetString("infoContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string infoContactLabel {
            get {
                return ResourceManager.GetString("infoContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string infoHeader {
            get {
                return ResourceManager.GetString("infoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toggle stop and boost by tapping game status bar.
        /// </summary>
        internal static string infoHowtoBoost {
            get {
                return ResourceManager.GetString("infoHowtoBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com.
        /// </summary>
        internal static string infoHowtoContent {
            get {
                return ResourceManager.GetString("infoHowtoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game is over when two trains collide or a station is full.
        /// </summary>
        internal static string infoHowtoEnd {
            get {
                return ResourceManager.GetString("infoHowtoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play:.
        /// </summary>
        internal static string infoHowtoLabel {
            get {
                return ResourceManager.GetString("infoHowtoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the ealier you pick up passengers the more points you will get.
        /// </summary>
        internal static string infoHowToMoney {
            get {
                return ResourceManager.GetString("infoHowToMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick up colored passengers with the corresponding train.
        /// </summary>
        internal static string infoHowToPassenger {
            get {
                return ResourceManager.GetString("infoHowToPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap train to do an emergency stop or speed boost.
        /// </summary>
        internal static string infoHowToStop {
            get {
                return ResourceManager.GetString("infoHowToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap switches to change train destination.
        /// </summary>
        internal static string infoHowToSwitch {
            get {
                return ResourceManager.GetString("infoHowToSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.banjr.com.
        /// </summary>
        internal static string infoMusicContent {
            get {
                return ResourceManager.GetString("infoMusicContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with admission of.
        /// </summary>
        internal static string infoMusicContextAdmission {
            get {
                return ResourceManager.GetString("infoMusicContextAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music:.
        /// </summary>
        internal static string infoMusicLabel {
            get {
                return ResourceManager.GetString("infoMusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string infoVersion {
            get {
                return ResourceManager.GetString("infoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Course.
        /// </summary>
        internal static string level1Name {
            get {
                return ResourceManager.GetString("level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert Run.
        /// </summary>
        internal static string level2Name {
            get {
                return ResourceManager.GetString("level2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Wonderland.
        /// </summary>
        internal static string level3Name {
            get {
                return ResourceManager.GetString("level3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulcano Ashes.
        /// </summary>
        internal static string level4Name {
            get {
                return ResourceManager.GetString("level4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Summer.
        /// </summary>
        internal static string level5Name {
            get {
                return ResourceManager.GetString("level5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Done.
        /// </summary>
        internal static string levelAccomplished {
            get {
                return ResourceManager.GetString("levelAccomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - two trains.
        /// </summary>
        internal static string levelDescription1DR {
            get {
                return ResourceManager.GetString("levelDescription1DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - three trains.
        /// </summary>
        internal static string levelDescription1IS {
            get {
                return ResourceManager.GetString("levelDescription1IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - one train.
        /// </summary>
        internal static string levelDescription1TC {
            get {
                return ResourceManager.GetString("levelDescription1TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - three trains.
        /// </summary>
        internal static string levelDescription1VA {
            get {
                return ResourceManager.GetString("levelDescription1VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - three trains.
        /// </summary>
        internal static string levelDescription1WW {
            get {
                return ResourceManager.GetString("levelDescription1WW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 50 passengers.
        /// </summary>
        internal static string levelDescription2DR {
            get {
                return ResourceManager.GetString("levelDescription2DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 120 passengers.
        /// </summary>
        internal static string levelDescription2IS {
            get {
                return ResourceManager.GetString("levelDescription2IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 30 passengers.
        /// </summary>
        internal static string levelDescription2TC {
            get {
                return ResourceManager.GetString("levelDescription2TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 100 passengers.
        /// </summary>
        internal static string levelDescription2VA {
            get {
                return ResourceManager.GetString("levelDescription2VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 80 passengers.
        /// </summary>
        internal static string levelDescription2WW {
            get {
                return ResourceManager.GetString("levelDescription2WW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boosts.
        /// </summary>
        internal static string levelDescription3boost {
            get {
                return ResourceManager.GetString("levelDescription3boost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops.
        /// </summary>
        internal static string levelDescription3stop {
            get {
                return ResourceManager.GetString("levelDescription3stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string levelSelection {
            get {
                return ResourceManager.GetString("levelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new level unlocked.
        /// </summary>
        internal static string levelUnlocked {
            get {
                return ResourceManager.GetString("levelUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/games.
        /// </summary>
        internal static string moreGamesURL {
            get {
                return ResourceManager.GetString("moreGamesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/news/news.php.
        /// </summary>
        internal static string newsURL {
            get {
                return ResourceManager.GetString("newsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Stage.
        /// </summary>
        internal static string nextStage {
            get {
                return ResourceManager.GetString("nextStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/.
        /// </summary>
        internal static string phoebitURL {
            get {
                return ResourceManager.GetString("phoebitURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to station full.
        /// </summary>
        internal static string stationFull {
            get {
                return ResourceManager.GetString("stationFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap to continue.
        /// </summary>
        internal static string tapContinue {
            get {
                return ResourceManager.GetString("tapContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train added.
        /// </summary>
        internal static string trainAdded {
            get {
                return ResourceManager.GetString("trainAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train collision.
        /// </summary>
        internal static string trainCollision {
            get {
                return ResourceManager.GetString("trainCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
