//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyMadness.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyMadness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheater.
        /// </summary>
        internal static string AchievementCheater {
            get {
                return ResourceManager.GetString("AchievementCheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect all bonus item during a level.
        /// </summary>
        internal static string AchievementCheaterDescription {
            get {
                return ResourceManager.GetString("AchievementCheaterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driller Killer.
        /// </summary>
        internal static string AchievementDrillerKiller {
            get {
                return ResourceManager.GetString("AchievementDrillerKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish a level by drilling through the last line.
        /// </summary>
        internal static string AchievementDrillerKillerDescription {
            get {
                return ResourceManager.GetString("AchievementDrillerKillerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghost Buster.
        /// </summary>
        internal static string AchievementGhostBuster {
            get {
                return ResourceManager.GetString("AchievementGhostBuster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 3 mosters from the game.
        /// </summary>
        internal static string AchievementGhostBusterDescription {
            get {
                return ResourceManager.GetString("AchievementGhostBusterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icarus.
        /// </summary>
        internal static string AchievementIcarus {
            get {
                return ResourceManager.GetString("AchievementIcarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall down 3 lines without getting up in between.
        /// </summary>
        internal static string AchievementIcarusDescription {
            get {
                return ResourceManager.GetString("AchievementIcarusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lefty.
        /// </summary>
        internal static string AchievementLefty {
            get {
                return ResourceManager.GetString("AchievementLefty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use holes moving from left to right only.
        /// </summary>
        internal static string AchievementLeftyDescription {
            get {
                return ResourceManager.GetString("AchievementLeftyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall down 3 lines and recover at the bottom line.
        /// </summary>
        internal static string AchievementLuckyDevilDescription {
            get {
                return ResourceManager.GetString("AchievementLuckyDevilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newbie.
        /// </summary>
        internal static string AchievementNewbie {
            get {
                return ResourceManager.GetString("AchievementNewbie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No points at game end.
        /// </summary>
        internal static string AchievementNewbieDescription {
            get {
                return ResourceManager.GetString("AchievementNewbieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedy.
        /// </summary>
        internal static string AchievementSpeedyGonzales {
            get {
                return ResourceManager.GetString("AchievementSpeedyGonzales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish a level within 30 seconds.
        /// </summary>
        internal static string AchievementSpeedyGonzalesDescription {
            get {
                return ResourceManager.GetString("AchievementSpeedyGonzalesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stalker.
        /// </summary>
        internal static string AchievementStalker {
            get {
                return ResourceManager.GetString("AchievementStalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get stunned by 3 monsters without getting up in between.
        /// </summary>
        internal static string AchievementStalkerDescription {
            get {
                return ResourceManager.GetString("AchievementStalkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Monkey.
        /// </summary>
        internal static string AchievementSuper {
            get {
                return ResourceManager.GetString("AchievementSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach level 5 at difficulty hard.
        /// </summary>
        internal static string AchievementSuperDescription {
            get {
                return ResourceManager.GetString("AchievementSuperDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumbler.
        /// </summary>
        internal static string AchievementTumbler {
            get {
                return ResourceManager.GetString("AchievementTumbler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover 3 times from monster crashes.
        /// </summary>
        internal static string AchievementTumblerDescription {
            get {
                return ResourceManager.GetString("AchievementTumblerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Devil.
        /// </summary>
        internal static string AchievmentLuckyDevil {
            get {
                return ResourceManager.GetString("AchievmentLuckyDevil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasant.
        /// </summary>
        internal static string AchievmentPleasantJourney {
            get {
                return ResourceManager.GetString("AchievmentPleasantJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish a level without falling down or monster crash.
        /// </summary>
        internal static string AchievmentPleasantJourneyDescription {
            get {
                return ResourceManager.GetString("AchievmentPleasantJourneyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/games.
        /// </summary>
        internal static string moreGamesURL {
            get {
                return ResourceManager.GetString("moreGamesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/news/news.php.
        /// </summary>
        internal static string newsURL {
            get {
                return ResourceManager.GetString("newsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com/.
        /// </summary>
        internal static string phoebitURL {
            get {
                return ResourceManager.GetString("phoebitURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        internal static string strAward {
            get {
                return ResourceManager.GetString("strAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string strBack {
            get {
                return ResourceManager.GetString("strBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string strConcrats {
            get {
                return ResourceManager.GetString("strConcrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string strEasy {
            get {
                return ResourceManager.GetString("strEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username for the highscore list.
        /// </summary>
        internal static string strEnterUserName {
            get {
                return ResourceManager.GetString("strEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound FX.
        /// </summary>
        internal static string strFX {
            get {
                return ResourceManager.GetString("strFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string strGameOver {
            get {
                return ResourceManager.GetString("strGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string strHard {
            get {
                return ResourceManager.GetString("strHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string strHighScore {
            get {
                return ResourceManager.GetString("strHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time High.
        /// </summary>
        internal static string strHighScoreAll {
            get {
                return ResourceManager.GetString("strHighScoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string strHighScoreLocal {
            get {
                return ResourceManager.GetString("strHighScoreLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/requestscores_mm.php.
        /// </summary>
        internal static string strHighScoreRequestURL {
            get {
                return ResourceManager.GetString("strHighScoreRequestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://lars.msbase.de/highscores/newscore_mm.php.
        /// </summary>
        internal static string strHighScoreSendURL {
            get {
                return ResourceManager.GetString("strHighScoreSendURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string strhighScoreUpdate {
            get {
                return ResourceManager.GetString("strhighScoreUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ of the Week.
        /// </summary>
        internal static string strHighScoreWeek {
            get {
                return ResourceManager.GetString("strHighScoreWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string strInfo {
            get {
                return ResourceManager.GetString("strInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.soundjay.com.
        /// </summary>
        internal static string strInfoAudioContent {
            get {
                return ResourceManager.GetString("strInfoAudioContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and Music: .
        /// </summary>
        internal static string strInfoAudioLabel {
            get {
                return ResourceManager.GetString("strInfoAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monkey@phoebit.com.
        /// </summary>
        internal static string strInfoContactContent {
            get {
                return ResourceManager.GetString("strInfoContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact: .
        /// </summary>
        internal static string strInfoContactLabel {
            get {
                return ResourceManager.GetString("strInfoContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string strInfoHeader {
            get {
                return ResourceManager.GetString("strInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump when the hint appears.
        /// </summary>
        internal static string strInfoHint {
            get {
                return ResourceManager.GetString("strInfoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.phoebit.com.
        /// </summary>
        internal static string strInfoHowtoContent {
            get {
                return ResourceManager.GetString("strInfoHowtoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play: .
        /// </summary>
        internal static string strInfoHowtoLabel {
            get {
                return ResourceManager.GetString("strInfoHowtoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave at one side and enter at the other.
        /// </summary>
        internal static string strInfoLeave {
            get {
                return ResourceManager.GetString("strInfoLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t run into monsters.
        /// </summary>
        internal static string strInfoMonster {
            get {
                return ResourceManager.GetString("strInfoMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the display to jump.
        /// </summary>
        internal static string strInfoTap {
            get {
                return ResourceManager.GetString("strInfoTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt the phone to move the monkey.
        /// </summary>
        internal static string strInfoTilt {
            get {
                return ResourceManager.GetString("strInfoTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string strInfoVersion {
            get {
                return ResourceManager.GetString("strInfoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press A to jump.
        /// </summary>
        internal static string strInfoXboxJump {
            get {
                return ResourceManager.GetString("strInfoXboxJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left thumbstick to run.
        /// </summary>
        internal static string strInfoXBoxRun {
            get {
                return ResourceManager.GetString("strInfoXBoxRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string strLevel {
            get {
                return ResourceManager.GetString("strLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string strLevelGo {
            get {
                return ResourceManager.GetString("strLevelGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives.
        /// </summary>
        internal static string strLives {
            get {
                return ResourceManager.GetString("strLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string strMedium {
            get {
                return ResourceManager.GetString("strMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string strMusic {
            get {
                return ResourceManager.GetString("strMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Level.
        /// </summary>
        internal static string strNextLevel {
            get {
                return ResourceManager.GetString("strNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string strOptionAudio {
            get {
                return ResourceManager.GetString("strOptionAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string strOptionDifficulty {
            get {
                return ResourceManager.GetString("strOptionDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string strOptions {
            get {
                return ResourceManager.GetString("strOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string strOptionsUsername {
            get {
                return ResourceManager.GetString("strOptionsUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string strPlay {
            get {
                return ResourceManager.GetString("strPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string strPoints {
            get {
                return ResourceManager.GetString("strPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string strTime {
            get {
                return ResourceManager.GetString("strTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string strTrial {
            get {
                return ResourceManager.GetString("strTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Ads.
        /// </summary>
        internal static string strTrialAds {
            get {
                return ResourceManager.GetString("strTrialAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Monkey Madness on Marketplace.
        /// </summary>
        internal static string strTrialBye {
            get {
                return ResourceManager.GetString("strTrialBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Levels.
        /// </summary>
        internal static string strTrialLevel {
            get {
                return ResourceManager.GetString("strTrialLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Monsters.
        /// </summary>
        internal static string strTrialMonster {
            get {
                return ResourceManager.GetString("strTrialMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
